name: waseet_cookies
description: Flutter plugin to read/clear Android WebView cookies via MethodChannel.
version: 0.1.2
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:               # ← تحت flutter: وليس في الجذر
    platforms:
      android:
        package: com.waseet.cookies
        pluginClass: WaseetCookiesPlugin
